# Generated by Django 3.1.3 on 2020-11-19 01:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201118_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustancia',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
