# Generated by Django 3.1.3 on 2020-11-21 18:46

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201118_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de categoria')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de solicitante')),
                ('cedula', models.CharField(max_length=10, verbose_name='Numero de cedula')),
                ('telefono', models.CharField(max_length=10, verbose_name='Numero de telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'db_table': 'solicitante',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['id'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventariados'},
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=datetime.datetime.now)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('solicitante_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'ordering': ['id'],
            },
        ),
    ]
